const products = [
  {
    image: "/assets/CartImg/pic1.svg",
    name: "Gaming Controller AK-900",
    price: 59,
    oldPrice: 99,
    rating: { stars: 4, count: 120 },
    discount: "-40%",
  },
  {
    image: "/assets/CartImg/pic2.svg",
    name: "GP11 Gaming Mouse",
    price: 560,
    oldPrice: 799,
    rating: { stars: 2.5, count: 85 },
    discount: "-30%",
  },
  {
    image: "/assets/CartImg/pic3.svg",
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: { stars: 4, count: 230 },
    discount: "-25%",
  },
  {
    image: "/assets/CartImg/pic4.svg",
    name: "S-Series Comfort Chair",
    price: 375,
    oldPrice: 499,
    rating: { stars: 1.5, count: 190 },
    discount: "-24%",
  },
  {
    image: "/assets/CartImg/pic5.svg",
    name: "ASUS ROG Gaming Laptop",
    price: 700,
    oldPrice: 950,
    rating: { stars: 5, count: 65 },
    discount: "-26%",
  },
  {
    image: "/assets/CartImg/pic6.svg",
    name: "CANON EOS DSLR Camera",
    price: 360,
    oldPrice: 450,
    rating: { stars: 5, count: 140 },
    discount: "-20%",
  },
  {
    image: "/assets/CartImg/pic7.svg",
    name: "JBL Bluetooth Speaker",
    price: 180,
    oldPrice: 250,
    rating: { stars: 5, count: 210 },
    discount: "-28%",
  },
  {
    image: "/assets/CartImg/pic8.svg",
    name: "Gucci Duffle Bag",
    price: 960,
    oldPrice: 1200,
    rating: { stars: 5, count: 75 },
    discount: "-20%",
  },
  {
    image: "/assets/CartImg/pic9.svg",
    name: "RGB Liquid CPU Cooler",
    price: 160,
    oldPrice: 220,
    rating: { stars: 5, count: 95 },
    discount: "-27%",
  },
    {
    image: "/assets/CartImg/pic2.svg",
    name: "GP11 Gaming Mouse",
    price: 560,
    oldPrice: 799,
    rating: { stars: 5, count: 85 },
    discount: "-30%",
  },
  {
    image: "/assets/CartImg/pic10.svg",
    name: "Quilted Satin Jacket",
    price: 660,
    oldPrice: 799,
    rating: { stars: 4, count: 110 },
    discount: "-17%",
  },
  {
    image: "/assets/CartImg/pic11.svg",
    name: "Kids Electric Car",
    price: 960,
    oldPrice: 1200,
    rating: { stars: 5, count: 150 },
    discount: "-20%",
  },
    {
    image: "/assets/CartImg/pic4.svg",
    name: "S-Series Comfort Chair",
    price: 375,
    oldPrice: 499,
    rating: { stars: 5, count: 190 },
    discount: "-24%",
  },
];

export default products;
