const products = [
  {
    image: "src/assets/CartImg/ak-900-01-500x500 1.svg",
    name: "Gaming Controller AK-900",
    price: 59,
    oldPrice: 99,
    rating: { stars: 4, count: 120 },
    discount: "-40%", 
  },
  {
    image: "src/assets/CartImg/71RdoeXxtrL 1.svg",
    name: "GP11 Gaming Mouse",
    price: 560,
    oldPrice: 799,
    rating: { stars: 2.5, count: 85 },
    discount: "-30%",
  },
  {
    image: "src/assets/CartImg/547953_9C2ST_8746_001_082_0000_Light-Gucci-Savoy-medium-duffle-bag 1.svg",
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: { stars: 4, count: 230 },
    discount: "-25%",
  },
  {
    image: "src/assets/CartImg/eos-250d-03-500x500 1.svg",
    name: "S-Series Comfort Chair",
    price: 375,
    oldPrice: 499,
    rating: { stars: 1.5, count: 190 },
    discount: "-24%",
  },
  {
    image: "src/assets/CartImg/Frame 611.svg",
    name: "ASUS ROG Gaming Laptop",
    price: 700,
    oldPrice: 950,
    rating: { stars: 5, count: 65 },
    discount: "-26%",
  },
  {
    image: "src/assets/CartImg/g27cq4-500x500 1.svg",
    name: "CANON EOS DSLR Camera",
    price: 360,
    oldPrice: 450,
    rating: { stars: 4, count: 140 },
    discount: "-20%",
  },
  {
    image: "src/assets/CartImg/gammaxx-l240-argb-1-500x500 1.svg",
    name: "JBL Bluetooth Speaker",
    price: 180,
    oldPrice: 250,
    rating: { stars: 5, count: 210 },
    discount: "-28%",
  },
  {
    image: "src/assets/CartImg/GP11_PRD3 1.svg",
    name: "Gucci Duffle Bag",
    price: 960,
    oldPrice: 1200,
    rating: { stars: 4, count: 75 },
    discount: "-20%",
  },
  {
    image: "src/assets/CartImg/ideapad-gaming-3i-01-500x500 1.svg",
    name: "RGB Liquid CPU Cooler",
    price: 160,
    oldPrice: 220,
    rating: { stars: 5, count: 95 },
    discount: "-27%",
  },
  {
    image: "src/assets/CartImg/sam-moghadam-khamseh-kvmdsTrGOBM-unsplash 1.svg",
    name: "Quilted Satin Jacket",
    price: 660,
    oldPrice: 799,
    rating: { stars: 4, count: 110 },
    discount: "-17%",
  },
  {
    image: "src/assets/CartImg/sam-moghadam-khamseh-kvmdsTrGOBM-unsplash 1.svg",
    name: "Kids Electric Car",
    price: 960,
    oldPrice: 1200,
    rating: { stars: 5, count: 150 },
    discount: "-20%",
  },
];

export default products;
